/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wywonderfulplayer_WonderfulPlayer */

#ifndef _Included_com_example_wywonderfulplayer_WonderfulPlayer
#define _Included_com_example_wywonderfulplayer_WonderfulPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wywonderfulplayer_WonderfulPlayer
 * Method:    prepareNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_wywonderfulplayer_WonderfulPlayer_prepareNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_wywonderfulplayer_WonderfulPlayer
 * Method:    startNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_wywonderfulplayer_WonderfulPlayer_startNative
  (JNIEnv *, jobject);

/*
 * Class:     com_example_wywonderfulplayer_WonderfulPlayer
 * Method:    stopNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_wywonderfulplayer_WonderfulPlayer_stopNative
  (JNIEnv *, jobject);

extern "C"
JNIEXPORT void JNICALL Java_com_example_wywonderfulplayer_WonderfulPlayer_setSurfaceNative(JNIEnv *env, jobject thizz,jobject surface);

#ifdef __cplusplus
}
#endif
#endif
